name: Run Python Tests

# Ejecuta el workflow en cada push o pull request a la rama main
on:
  push:  # Ejecutar en cualquier push a cualquier rama
    branches: 
      - '**'  # '**' significa todas las ramas
  pull_request:  # También ejecuta en pull requests a cualquier rama
    branches: 
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Check out the repository
      - name: Check out the repository
        uses: actions/checkout@v3

      # Paso 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Ajusta la versión de Python según tus necesidades

      # Paso 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dependencias.txt  # Asegúrate de tener un archivo requirements.txt
          
      # Paso 4: Run tests
      - name: Run tests
        run: |
          python -m unittest discover
